from sqlalchemy import Column, Float, Integer, String

from iconic.model.base import Base


class CustomerPaymentModel(Base):
    __tablename__ = 'customer_payment'
    customer_id = Column(String, primary_key=True)
    days_since_first_order = Column(Integer)
    days_since_last_order = Column(Integer)
    is_newsletter_subscriber = Column(String)
    orders = Column(Integer)
    items = Column(Integer)
    cancels = Column(Integer)
    returns = Column(Integer)
    different_addresses = Column(Integer)
    shipping_addresses = Column(Integer)
    devices = Column(Integer)
    vouchers = Column(Integer)
    cc_payments = Column(Integer)
    paypal_payments = Column(Integer)
    afterpay_payments = Column(Integer)
    apple_payments = Column(Integer)
    female_items = Column(Integer)
    male_items = Column(Integer)
    unisex_items = Column(Integer)
    wapp_items = Column(Integer)
    wftw_items = Column(Integer)
    mapp_items = Column(Integer)
    wacc_items = Column(Integer)
    macc_items = Column(Integer)
    mftw_items = Column(Integer)
    wspt_items = Column(Integer)
    mspt_items = Column(Integer)
    curvy_items = Column(Integer)
    sacc_items = Column(Integer)
    msite_orders = Column(Integer)
    desktop_orders = Column(Integer)
    android_orders = Column(Integer)
    ios_orders = Column(Integer)
    other_device_orders = Column(Integer)
    work_orders = Column(Integer)
    home_orders = Column(Integer)
    parcelpoint_orders = Column(Integer)
    other_collection_orders = Column(Integer)
    average_discount_onoffer = Column(Float)
    average_discount_used = Column(Float)
    revenue = Column(Float)
